### ISSUE TITLE
without changing anything Error: appkey is incorrect 'er_invalid_appkey'

### ISSUE THREAD

**Issue by jarg** [MickMake/GoSungro#102]
hello, since today without doing anything I get an error in the key.

`[09:36:41] INFO: Login to iSolarCloud using gateway https://gateway.isolarcloud.eu ...
Error: appkey is incorrect 'er_invalid_appkey'
Usage:
  GoSungrow api login [flags]`

The key not change: 
93D72E60331ABDCDC7B39ADC2D1F32B3

Regards

**Comment by Falkoh150** [comment]
Same here.

**Comment by lupus78** [comment]
Same for me. The issue is the same as #101

**Comment by jarg** [comment]
> Same for me. The issue is the same as #101

I close this and y comment in #101.

Thanks.

**Comment by Martin69R** [comment]
same to me

**Comment by ltw001** [comment]
same to me (fresh installation)

**Comment by Paraphraser** [comment]
@Martin69R @ltw001 a fresh installation doesn't solve the underlying problem. You **must** also follow the steps in [this gist](https://gist.github.com/Paraphraser/cad3b0aa6428c58ee87bc835ac12ed37) to get GoSungrow working again.

**Comment by Martin69R** [comment]
Hi Pilll!
Thanks for your reply and your explanations!
I´m quite new on home assistant and so familiar with simple procedures.
My goal is only to read the power meters and the integration in the energy dashboard.
Is this possible on a simple way?
Thanks for answer in advance!
