### ISSUE TITLE
Issue with Energy dashboard in HA

### ISSUE THREAD

**Issue by grf692** [MickMake/GoSungro#109]
Hi,

I have an issue I don't manage to fix and wish to ask if one of you had the same behavior maybe.

In the Energy dashboard settings page, I've set the "today_energy" sensor to be used as Solar production.

When I look at the history of this sensor in HA I get the behavior I believe I should expect, everyday at midnight it is reset to 0 as you can see in the screenshot here:

![image](https://github.com/MickMake/GoSungrow/assets/30925906/ee61b879-1295-46b5-bbd6-38beccb6cc92)

But in my Energy Dashboard it shows as negative value everyday at midnight:

![image](https://github.com/MickMake/GoSungrow/assets/30925906/563eaaf8-cfae-48f8-89ff-8b7e84999ac3)

May anyone give me a hint on how to fix this please?
Or what is the full name of the "sensor" you use? (I am in Europe/Sweden)
Mine is GoSungrow xxx - SUNGROW GoSungrow getPsDetail.xxx.today_energy

Thanks!

**Comment by JohnFLoki** [comment]
That is because the sensor is resetting every day, but because it doesn't update before 0:00 Home Assistant calculates like that.

You can create an Utility Meter with "Periodically resetting" to address that.

**Comment by grf692** [comment]
Thanks, I was not aware of these "creatures"!
Now I've set a helpers as utility meter and it seems to work like a charm.

**Comment by grf692** [comment]
Thanks, I was not aware of these "creatures"!
Now I've set a helpers as utility meter and it seems to work like a charm.

**Comment by mazvone** [comment]
How did you that, can you write step by step?

**Comment by JohnFLoki** [comment]
@mazvone You go to settings -> Devices & Services -> Helpers (topside) -> create Helper -> Utility Meter ->
Name: you do you
Input sensor: sensor.[...]today_energy
...
Periodically resetting: yes

Then add it to your energy dashboard when it so its first value.
