### ISSUE TITLE
Complete newbie to Go - how to get started?

### ISSUE THREAD

**Issue by baljo** [MickMake/GoSungro#84]
Not sure how to get started, this is what I've done:
- cloned the repo on my Win10-machine
- installed Go and ensured it is working

When trying this in the Command Prompt: 
`./bin/GoSungrow config write --user=USERNAME --password=PASSWORD`
I get:
`'bin\GoSungrow' is not recognized as an internal or external command, operable program or batch file.`

The reason is probably that the only files in the GoSungrow\bin-folder are: docker.sh, release.sh, strip.sh

What am I missing here? Do I need to somehow compile/build something?

**Comment by baljo** [comment]
Just shooting in the dark and tried with `go build`

Got this:

**C:\Users\thv\Dropbox\Github\GoSungrow>go build**
iSolarCloud\api\GoStruct\gojson\funcs.go:45:2: github.com/MickMake/GoUnify@v0.0.0-00010101000000-000000000000: replacement directory ../../GoUnify does not exist
iSolarCloud\api\file.go:9:2: github.com/MickMake/GoUnify@v0.0.0-00010101000000-000000000000: replacement directory ../../GoUnify does not exist
cmdHassio\config.go:6:2: github.com/MickMake/GoUnify@v0.0.0-00010101000000-000000000000: replacement directory ../../GoUnify does not exist
cmd\commands.go:6:2: github.com/MickMake/GoUnify@v0.0.0-00010101000000-000000000000: replacement directory ../../GoUnify does not exist
cmd\cmd_api.go:10:2: github.com/MickMake/GoUnify@v0.0.0-00010101000000-000000000000: replacement directory ../../GoUnify does not exist
cmd\cmd_api.go:11:2: github.com/MickMake/GoUnify@v0.0.0-00010101000000-000000000000: replacement directory ../../GoUnify does not exist
`

**Comment by iyertalks** [comment]
I am stuck with the same issue. Any help is highly appreciated.

**Comment by Inca1777** [comment]
I had the same issue today as well.

GoSunGrow "go build" depends on https://github.com/MickMake/GoUnify, so I downloaded that first.

Make sure you get the location right as it expects it "../../GoUnify"  (for which I've used a soft link to match my download directory) 

With the GoUnify dependency met, GoSungGrow built OK for me. 

As last step run "go install" - which given proper go setup should put the binary in $GOPATH/bin

**Comment by baljo** [comment]
> I had the same issue today as well.
> 
> GoSunGrow "go build" depends on https://github.com/MickMake/GoUnify, so I downloaded that first.
> 
> Make sure you get the location right as it expects it "../../GoUnify" (for which I've used a soft link to match my download directory)
> 
> With the GoUnify dependency met, GoSungGrow built OK for me.
> 
> As last step run "go install" - which given proper go setup should put the binary in $GOPATH/bin

Many many thanks, got it to work now! Had not downloaded GoUnify initially, thought it'd be done automagically, Had also some problems with 404, but by changing to correct EU-server and stripping out the last '/', it works now

**Comment by Paraphraser** [comment]
I've mentioned this on #87 but I'm also mentioning it here in case anyone else who is having trouble compiling GoSungrow reads this issue:

* Please try following [this gist](https://gist.github.com/Paraphraser/cad3b0aa6428c58ee87bc835ac12ed37) and see if it helps solve your problem
